export const titleOptions = ['Mr', 'Ms', 'Miss', 'Mrs'];
export const maritalStatusOptions = [
  'Never Married',
  'Divorced',
  'Widowed',
  'Separated',
];
export const ageRanges = [
  '18–24',
  '25–29',
  '30–34',
  '35–39',
  '40–44',
  '45–49',
  '50+',
  'No preference',
];
// Country to flag emoji mapping
const countryFlags: Record<string, string> = {
  Afghanistan: '🇦🇫',
  Albania: '🇦🇱',
  Algeria: '🇩🇿',
  Andorra: '🇦🇩',
  Angola: '🇦🇴',
  'Antigua and Barbuda': '🇦🇬',
  Argentina: '🇦🇷',
  Armenia: '🇦🇲',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Azerbaijan: '🇦🇿',
  Bahamas: '🇧🇸',
  Bahrain: '🇧🇭',
  Bangladesh: '🇧🇩',
  Barbados: '🇧🇧',
  Belarus: '🇧🇾',
  Belgium: '🇧🇪',
  Belize: '🇧🇿',
  Benin: '🇧🇯',
  Bhutan: '🇧🇹',
  Bolivia: '🇧🇴',
  'Bosnia and Herzegovina': '🇧🇦',
  Botswana: '🇧🇼',
  Brazil: '🇧🇷',
  Brunei: '🇧🇳',
  Bulgaria: '🇧🇬',
  'Burkina Faso': '🇧🇫',
  Burundi: '🇧🇮',
  Cambodia: '🇰🇭',
  Cameroon: '🇨🇲',
  Canada: '🇨🇦',
  'Cape Verde': '🇨🇻',
  'Central African Republic': '🇨🇫',
  Chad: '🇹🇩',
  Chile: '🇨🇱',
  China: '🇨🇳',
  Colombia: '🇨🇴',
  Comoros: '🇰🇲',
  'Costa Rica': '🇨🇷',
  Croatia: '🇭🇷',
  Cuba: '🇨🇺',
  Cyprus: '🇨🇾',
  'Czech Republic': '🇨🇿',
  Denmark: '🇩🇰',
  Djibouti: '🇩🇯',
  Dominica: '🇩🇲',
  'Dominican Republic': '🇩🇴',
  Ecuador: '🇪🇨',
  Egypt: '🇪🇬',
  'El Salvador': '🇸🇻',
  'Equatorial Guinea': '🇬🇶',
  Eritrea: '🇪🇷',
  Estonia: '🇪🇪',
  Eswatini: '🇸🇿',
  Ethiopia: '🇪🇹',
  Fiji: '🇫🇯',
  Finland: '🇫🇮',
  France: '🇫🇷',
  Gabon: '🇬🇦',
  Gambia: '🇬🇲',
  Georgia: '🇬🇪',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Greece: '🇬🇷',
  Grenada: '🇬🇩',
  Guatemala: '🇬🇹',
  Guinea: '🇬🇳',
  'Guinea-Bissau': '🇬🇼',
  Guyana: '🇬🇾',
  Haiti: '🇭🇹',
  Honduras: '🇭🇳',
  Hungary: '🇭🇺',
  Iceland: '🇮🇸',
  India: '🇮🇳',
  Indonesia: '🇮🇩',
  Iran: '🇮🇷',
  Iraq: '🇮🇶',
  Ireland: '🇮🇪',
  Israel: '🇮🇱',
  Italy: '🇮🇹',
  Jamaica: '🇯🇲',
  Japan: '🇯🇵',
  Jordan: '🇯🇴',
  Kazakhstan: '🇰🇿',
  Kenya: '🇰🇪',
  Kiribati: '🇰🇮',
  Kuwait: '🇰🇼',
  Kyrgyzstan: '🇰🇬',
  Laos: '🇱🇦',
  Latvia: '🇱🇻',
  Lebanon: '🇱🇧',
  Lesotho: '🇱🇸',
  Liberia: '🇱🇷',
  Libya: '🇱🇾',
  Liechtenstein: '🇱🇮',
  Lithuania: '🇱🇹',
  Luxembourg: '🇱🇺',
  Madagascar: '🇲🇬',
  Malawi: '🇲🇼',
  Malaysia: '🇲🇾',
  Maldives: '🇲🇻',
  Mali: '🇲🇱',
  Malta: '🇲🇹',
  'Marshall Islands': '🇲🇭',
  Mauritania: '🇲🇷',
  Mauritius: '🇲🇺',
  Mexico: '🇲🇽',
  Micronesia: '🇫🇲',
  Moldova: '🇲🇩',
  Monaco: '🇲🇨',
  Mongolia: '🇲🇳',
  Montenegro: '🇲🇪',
  Morocco: '🇲🇦',
  Mozambique: '🇲🇿',
  Myanmar: '🇲🇲',
  Namibia: '🇳🇦',
  Nauru: '🇳🇷',
  Nepal: '🇳🇵',
  Netherlands: '🇳🇱',
  'New Zealand': '🇳🇿',
  Nicaragua: '🇳🇮',
  Niger: '🇳🇪',
  Nigeria: '🇳🇬',
  'North Korea': '🇰🇵',
  'North Macedonia': '🇲🇰',
  Norway: '🇳🇴',
  Oman: '🇴🇲',
  Pakistan: '🇵🇰',
  Palau: '🇵🇼',
  Panama: '🇵🇦',
  'Papua New Guinea': '🇵🇬',
  Paraguay: '🇵🇾',
  Peru: '🇵🇪',
  Philippines: '🇵🇭',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  Qatar: '🇶🇦',
  Romania: '🇷🇴',
  Russia: '🇷🇺',
  Rwanda: '🇷🇼',
  'Saint Kitts and Nevis': '🇰🇳',
  'Saint Lucia': '🇱🇨',
  'Saint Vincent and the Grenadines': '🇻🇨',
  Samoa: '🇼🇸',
  'San Marino': '🇸🇲',
  'Sao Tome and Principe': '🇸🇹',
  'Saudi Arabia': '🇸🇦',
  Senegal: '🇸🇳',
  Serbia: '🇷🇸',
  Seychelles: '🇸🇨',
  'Sierra Leone': '🇸🇱',
  Singapore: '🇸🇬',
  Slovakia: '🇸🇰',
  Slovenia: '🇸🇮',
  'Solomon Islands': '🇸🇧',
  Somalia: '🇸🇴',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  'South Sudan': '🇸🇸',
  Spain: '🇪🇸',
  'Sri Lanka': '🇱🇰',
  Sudan: '🇸🇩',
  Suriname: '🇸🇷',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Syria: '🇸🇾',
  Taiwan: '🇹🇼',
  Tajikistan: '🇹🇯',
  Tanzania: '🇹🇿',
  Thailand: '🇹🇭',
  'Timor-Leste': '🇹🇱',
  Togo: '🇹🇬',
  Tonga: '🇹🇴',
  'Trinidad and Tobago': '🇹🇹',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  Turkmenistan: '🇹🇲',
  Tuvalu: '🇹🇻',
  Uganda: '🇺🇬',
  Ukraine: '🇺🇦',
  'United Arab Emirates': '🇦🇪',
  'United Kingdom': '🇬🇧',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Uzbekistan: '🇺🇿',
  Vanuatu: '🇻🇺',
  'Vatican City': '🇻🇦',
  Venezuela: '🇻🇪',
  Vietnam: '🇻🇳',
  Yemen: '🇾🇪',
  Zambia: '🇿🇲',
  Zimbabwe: '🇿🇼',
};

// Country names array
const countryNames = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

// Export locationOptions as array of objects with name, flag, and value
export const locationOptions = countryNames.map(country => ({
  name: country,
  flag: countryFlags[country] || '🏳️',
  value: country, // For backward compatibility
}));

// Helper function to get flag for a country name (for backward compatibility)
export const getCountryFlag = (countryName: string): string => {
  return countryFlags[countryName] || '🏳️';
};

// Helper function to format country display with flag
export const formatCountryWithFlag = (countryName: string): string => {
  const flag = countryFlags[countryName] || '🏳️';
  return `${flag} ${countryName}`;
};

export const religiusBackgroundOptions = [
  'Very Religious',
  'Moderately Religious',
  'Slightly Religious',
  'Not Religious / Secular',
  'Spiritual but not Religious',
  'Prefer not to say',
];
export const partnerReligionImportanceOptions = [
  'Extremely Important',
  'Very Important',
  'Somewhat Important',
  'Not Very Important',
  'Not Important at All',
  'Prefer not to say',
];
export const partnerSameEthnicityOptions = [
  'Yes, strongly prefer',
  'Somewhat prefer',
  'No preference',
];
export const religionOptions = [
  'Islam',
  'Hinduism',
  'Christianity',
  'Sikhism',
  'Buddhism',
  'Jainism',
  'Judaism',
  'Atheist',
  'Agnostic',
  'Prefer not to say',
];
export const IslamSectionOptions = [
  'Sunni',
  'Brelvi',
  'Deobandi',
  'Ahl-e-Hadith',
  'Shia',
  'Ismaili',
  'Zaidi',
  'Prefer not to say',
];
export const HinduismSectionOptions = [
  'Vaishnavism',
  'Shaivism',
  'Shaktism',
  'Smartism',
  'Prefer not to say',
];
export const ChristianitySectionOptions = [
  'Catholicism',
  'Protestantism',
  'Lutheran',
  'Anglican',
  'Methodist',
  'Baptist',
  'Presbyterian',
  'Eastern Orthodoxy',
  'Prefer not to say',
];
export const SikhismSectionOptions = [
  'Khalsa',
  'Nanakpanthi',
  'Udasi',
  'Nirmala',
  'Prefer not to say',
];
export const BuddhismSectionOptions = [
  'Theravada',
  'Mahayana',
  'Vajrayana',
  'Zen',
  'Prefer not to say',
];
export const JainismSectionOptions = [
  'Digambara',
  'Svetambara',
  'Prefer not to say',
];
export const JudaismSectionOptions = [
  'Orthodox',
  'Conservative',
  'Reform',
  'Reconstructionist',
  'Prefer not to say',
];

export const relationshipPreferenceOptions = [
  'Not open to Polygamy',
  'Polygamy',
  'Prefer not to say',
];

export const castePakistan = [
  'Rajput',
  'Jutt',
  'Arain',
  'Sheikh',
  'Syed',
  'Gujjar',
  'Malik',
  'Awan',
  'Butt',
  'Chaudhry',
  'Pathan',
  'Pashtun',
  'Baloch',
  'Mughal',
  'Qureshi',
  'Ansari',
  'Hashmi',
  'Abbasi',
  'Siddiqui',
  'Farooqi',
  'Usmani',
  'Mirza',
  'Khan',
  'Khattak',
  'Afridi',
  'Yousafzai',
  'Leghari',
  'Mazari',
  'Jamali',
  'Mengal',
  'Bhatti',
  'Rana',
  'Jatoi',
  'Khar',
  'Niazi',
  'Lodhi',
  'Paracha',
  'Tareen',
  'Achakzai',
  'Bajwa',
  'Cheema',
  'Sandhu',
  'Warraich',
  'Gondal',
  'Sial',
  'Tiwana',
  'Chandio',
  'Kalhoro',
  'Soomro',
  'Junejo',
  'Panhwar',
  'Talpur',
  'Rind',
  'Bugti',
  'Marri',
  'Durrani',
  'Bangash',
  'Orakzai',
  'Kakar',
  'Shah',
  'Pirzada',
  'Gilani',
  'No Preference',
  'Other',
];
export const casteIndia = [
  'Brahmin',
  'Kshatriya',
  'Vaishya',
  'Shudra',
  'Kayastha',
  'Rajput',
  'Jat',
  'Yadav',
  'Kurmi',
  'Gupta',
  'Agarwal',
  'Baniya',
  'Marwari',
  'Jain',
  'Patel',
  'Patidar',
  'Shah',
  'Mehta',
  'Iyer',
  'Iyengar',
  'Reddy',
  'Naidu',
  'Nair',
  'Menon',
  'Pillai',
  'Chettiar',
  'Gounder',
  'Lingayat',
  'Vokkaliga',
  'Kamma',
  'Bhumihar',
  'Thakur',
  'Chamar',
  'Jatav',
  'Mahar',
  'Mali',
  'Koli',
  'Gujjar',
  'Ahir',
  'Pathan',
  'Sheikh',
  'Syed',
  'No Preference',
  'Other',
];
export const casteAfghanistan = [
  'Pashtun',
  'Durrani',
  'Ghilzai',
  'Yousafzai',
  'Afridi',
  'Achakzai',
  'Kakar',
  'Tareen',
  'Tajik',
  'Panjsheri',
  'Badakhshi',
  'Hazara',
  'Uzbek',
  'Turkmen',
  'Aimaq',
  'Baloch',
  'Nuristani',
  'Pashai',
  'Sadat (Syed)',
  'Qizilbash',
  'Kuchi',
  'No Preference',
  'Other',
];

export const professionOptions = [
  // Medical & Healthcare
  'Doctor',
  'Nurse',
  'Surgeon',
  'Dentist',
  'Pharmacist',
  'Physiotherapist',
  'Veterinarian',
  'Psychologist',
  'Psychiatrist',
  'Medical Researcher',
  'Medical Technician',
  'Radiologist',
  'Anesthesiologist',
  'Cardiologist',
  'Pediatrician',
  'Gynecologist',
  'Dermatologist',
  'Ophthalmologist',
  'Orthopedic Surgeon',
  'Neurologist',
  'Oncologist',
  'General Practitioner',
  'Medical Assistant',
  'Healthcare Administrator',

  // Engineering & Technology
  'Software Engineer',
  'AI Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'Computer Engineer',
  'Electrical Engineer',
  'Mechanical Engineer',
  'Civil Engineer',
  'Chemical Engineer',
  'Aerospace Engineer',
  'Biomedical Engineer',
  'Environmental Engineer',
  'Industrial Engineer',
  'Network Engineer',
  'Systems Engineer',
  'DevOps Engineer',
  'Cloud Engineer',
  'Cybersecurity Engineer',
  'Robotics Engineer',
  'Telecommunications Engineer',
  'IT Consultant',
  'IT Manager',
  'Web Developer',
  'Mobile App Developer',
  'Game Developer',
  'UI/UX Designer',
  'Product Manager',
  'Technical Writer',

  // Business & Finance
  'Business Owner',
  'Entrepreneur',
  'CEO / Executive',
  'Business Consultant',
  'Management Consultant',
  'Accountant',
  'Financial Analyst',
  'Investment Banker',
  'Financial Advisor',
  'Banker',
  'Auditor',
  'Tax Consultant',
  'Real Estate Agent',
  'Real Estate Developer',
  'Marketing Manager',
  'Sales Manager',
  'Business Analyst',
  'Operations Manager',
  'HR Manager',
  'Project Manager',
  'Supply Chain Manager',
  'Retail Manager',

  // Legal
  'Lawyer',
  'Attorney',
  'Judge',
  'Legal Advisor',
  'Paralegal',
  'Corporate Lawyer',
  'Criminal Lawyer',
  'Family Lawyer',
  'Immigration Lawyer',

  // Education
  'Teacher',
  'Professor',
  'Lecturer',
  'Principal',
  'School Administrator',
  'Education Consultant',
  'Tutor',
  'Researcher',
  'Academic',

  // Creative & Media
  'Graphic Designer',
  'Interior Designer',
  'Fashion Designer',
  'Architect',
  'Artist',
  'Photographer',
  'Videographer',
  'Video Editor',
  'Animator',
  'Writer',
  'Journalist',
  'Editor',
  'Content Creator',
  'Social Media Manager',
  'Marketing Specialist',
  'Public Relations Specialist',
  'Advertising Executive',
  'Musician',
  'Actor',
  'Director',
  'Producer',

  // Science & Research
  'Scientist',
  'Research Scientist',
  'Biologist',
  'Chemist',
  'Physicist',
  'Mathematician',
  'Statistician',
  'Geologist',
  'Astronomer',
  'Environmental Scientist',
  'Laboratory Technician',

  // Aviation & Transportation
  'Pilot',
  'Flight Attendant',
  'Air Traffic Controller',
  'Aircraft Engineer',
  'Ship Captain',
  'Logistics Coordinator',

  // Hospitality & Service
  'Chef',
  'Restaurant Manager',
  'Hotel Manager',
  'Event Planner',
  'Travel Agent',
  'Tour Guide',
  'Caterer',

  // Government & Public Service
  'Government Official',
  'Politician',
  'Diplomat',
  'Police Officer',
  'Firefighter',
  'Military Officer',
  'Public Administrator',
  'Social Worker',
  'Non-Profit Manager',

  // Skilled Trades
  'Electrician',
  'Plumber',
  'Carpenter',
  'Mechanic',
  'Welder',
  'Construction Manager',
  'Contractor',
  'HVAC Technician',

  // Other Professions
  'Consultant',
  'Freelancer',
  'Self-Employed',
  'Student',
  'Homemaker',
  'Retired',
  'Unemployed',
  'Prefer not to say',
];

export const educationOptions = [
  'No formal education',
  'High School',
  'Associate degree',
  "Bachelor's Degree",
  "Master's Degree",
  'Doctorate / PhD',
  'Professional degree',
];

export const heightOptions = [
  '4\'5" (135 cm)',
  '4\'6" (137 cm)',
  '4\'7" (140 cm)',
  '4\'8" (142 cm)',
  '4\'9" (145 cm)',
  '4\'10" (147 cm)',
  '4\'11" (150 cm)',
  '5\'0" (152 cm)',
  '5\'1" (155 cm)',
  '5\'2" (157 cm)',
  '5\'3" (160 cm)',
  '5\'4" (163 cm)',
  '5\'5" (165 cm)',
  '5\'6" (168 cm)',
  '5\'7" (170 cm)',
  '5\'8" (173 cm)',
  '5\'9" (175 cm)',
  '5\'10" (178 cm)',
  '5\'11" (180 cm)',
  '6\'0" (183 cm)',
  '6\'1" (185 cm)',
  '6\'2" (188 cm)',
  '6\'3" (191 cm)',
  '6\'4" (193 cm)',
  '6\'5" (196 cm)',
  '6\'6" (198 cm)',
  '6\'7" (201 cm)',
  '6\'8" (203 cm)',
  '6\'9" (206 cm)',
  '6\'10" (208 cm)',
  '6\'11" (211 cm)',
  '7\'0" (213 cm)',
];

export const languagesOptions = [
  'English',
  'Urdu',
  'Arabic',
  'French',
  'Spanish',
  'German',
  'Hindi',
  'Bengali',
  'Punjabi',
  'Pashto',
  'Turkish',
  'Italian',
  'Portuguese',
  'Chinese (Mandarin)',
  'Japanese',
  'Korean',
  'Russian',
  'Swahili',
  'Tamil',
  'Chinese (Cantonese)',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Malay',
  'Tagalog (Filipino)',
  'Dutch',
  'Greek',
  'Polish',
  'Czech',
  'Romanian',
  'Hungarian',
  'Swedish',
  'Norwegian',
  'Danish',
  'Finnish',
  'Hebrew',
  'Persian (Farsi)',
  'Kurdish',
  'Azerbaijani',
  'Kazakh',
  'Ukrainian',
  'Bulgarian',
  'Serbian',
  'Croatian',
  'Bosnian',
  'Albanian',
  'Macedonian',
  'Slovenian',
  'Slovak',
  'Lithuanian',
  'Latvian',
  'Estonian',
  'Icelandic',
  'Irish',
  'Welsh',
  'Catalan',
  'Basque',
  'Galician',
  'Malayalam',
  'Telugu',
  'Kannada',
  'Gujarati',
  'Marathi',
  'Odia',
  'Assamese',
  'Nepali',
  'Sinhala',
  'Burmese',
  'Khmer',
  'Lao',
  'Mongolian',
  'Georgian',
  'Armenian',
  'Amharic',
  'Hausa',
  'Yoruba',
  'Igbo',
  'Zulu',
  'Xhosa',
  'Afrikaans',
  'Somali',
  'Oromo',
];

export const familyDetailsOptions = [
  'Parents',
  'Siblings',
  'Children',
  'Other',
];

export const interestsOptions = [
  'Photography',
  'Fitness & Gym',
  'Hiking & Outdoors',
  'Gaming',
  'Art & Painting',
  'Technology & Gadgets',
  'Meditation & Yoga',
  'Writing & Blogging',
  'Travel & Adventure',
  'Cooking & Baking',
  'Volunteering',
  'Music & Concerts',
  'Fashion & Style',
  'Movies & Series',
  'Entrepreneurship',
  'Dancing',
  'Cycling',
  'Board Games & Puzzles',
  'Language Learning',
  'Reading & Books',
  'Food Exploring',
  'Nature & Scenic Views',
  'Socializing & Meetups',
  'Personal Growth',
  'Self-Care & Wellness',
  'Podcasts & Audiobooks',
  'Home & DIY Projects',
  'Learning New Skills',
  'Planning & Organizing',
  'Content Creation',
  'Minimalist Living',
  'Mindfulness',
  'Road Trips',
  'Casual Sports',
];

export const personalityOptions = [
  'Kind & Compassionate',
  'Honest & Loyal',
  'Calm & Patient',
  'Ambitious & Driven',
  'Confident',
  'Family-Oriented',
  'Responsible',
  'Funny & Playful',
  'Adventurous',
  'Creative',
  'Introverted',
  'Extroverted',
  'Empathetic',
  'Open-Minded',
  'Good Listener',
  'Optimistic',
  'Spontaneous',
  'Disciplined',
  'Supportive',
  'Independent',
];

export const months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const reportReasons = [
  'Inappropriate Content',
  'Fake Profile',
  'Harassment or Bullying',
  'Spam or Scam',
  'Underage User',
  'Inappropriate Photos',
  'Misleading Information',
  'Other',
];

export const pricingPlans = [
  { months: 1, price: '$9.99', perMonth: '$9.99/month' },
  { months: 3, price: '$24.99', perMonth: '$8.33/month', isBestValue: true },
  { months: 6, price: '$44.99', perMonth: '$7.50/month' },
];

export const comparisonFeatures = [
  { feature: 'See who likes you', free: false, premium: true },
  { feature: 'Advanced filters', free: false, premium: true },
  { feature: 'Unlimited likes', free: false, premium: true },
  { feature: 'Read receipts', free: false, premium: true },
  { feature: 'Boost profile', free: '1/month', premium: 'Unlimited' },
  { feature: 'See profile visitors', free: false, premium: true },
  { feature: 'Priority support', free: false, premium: true },
];
